#!/bin/bash

# Set up formatting
BOLD='\033[1m'
BOLD_RED='\033[1;31m'
BOLD_GREEN='\033[1;32m'
BOLD_CYAN='\033[1;36m'
END_COLOR='\033[0m'

INTERACTIVE=true
if [ "$#" -gt 0 ]; then
    INTERACTIVE=false
fi

press_enter_to_continue() {
    if [ "$INTERACTIVE" = true ]; then
        read -p "Press Enter to continue..."
    fi
}

run_setup_stepper() {
    echo -e "${BOLD_CYAN}====================================================${END_COLOR}"
    echo -e "${BOLD_CYAN}        Host Manager First-Run Setup Stepper        ${END_COLOR}"
    echo -e "${BOLD_CYAN}====================================================${END_COLOR}"
    echo "This wizard will help you configure your .settings file."
    echo ""

    # Check gh CLI first
    if ! command -v gh &>/dev/null; then
        echo -e "${BOLD_RED}ERROR:${END_COLOR} GitHub CLI (gh) is not installed."
        echo "Please install it first (e.g., 'brew install gh' on macOS)."
        exit 1
    fi

    # Check/authenticate GitHub CLI
    local GITHUB_USER=$(gh api user --jq .login 2>/dev/null)
    if [ -z "$GITHUB_USER" ]; then
        echo -e "${BOLD_RED}GitHub CLI (gh) is not authenticated.${END_COLOR}"
        echo "Authentication is required to synchronize the apps registry."
        read -p "Would you like to run 'gh auth login' now? (y/N): " auth_choice
        if [[ "$auth_choice" =~ ^[Yy]$ ]]; then
            gh auth login
            GITHUB_USER=$(gh api user --jq .login 2>/dev/null)
            if [ -z "$GITHUB_USER" ]; then
                echo -e "${BOLD_RED}Authentication failed. Please resolve and try again.${END_COLOR}"
                exit 1
            fi
        else
            echo -e "${BOLD_RED}GitHub authentication is required to proceed.${END_COLOR}"
            exit 1
        fi
    fi

    # Check other tools
    echo -e "\nChecking required dependencies..."
    for cmd in gcloud jq firebase; do
        if ! command -v $cmd &>/dev/null; then
            echo -e "${BOLD_RED}ERROR:${END_COLOR} $cmd CLI is not found."
            echo "Please install it before running setup."
            exit 1
        fi
    done
    echo -e "${BOLD_GREEN}Dependencies OK.${END_COLOR}\n"

    # Step 1: Projects Directory
    echo -e "${BOLD}Step 1: Projects Directory${END_COLOR}"
    echo "Enter the absolute path where your local projects will be scaffolded."
    read -p "Local projects directory [~/Projects]: " user_projects_dir
    if [ -z "$user_projects_dir" ]; then
        user_projects_dir="~/Projects"
    fi
    echo ""

    # Step 2: Google Cloud Billing Account ID
    echo -e "${BOLD}Step 2: Google Cloud Billing Account ID${END_COLOR}"
    echo "Enter your GCP / Firebase Billing Account ID (used to enable the Blaze plan)."
    read -p "Billing Account ID: " user_billing_id
    while [ -z "$user_billing_id" ]; do
        echo -e "${BOLD_RED}Required:${END_COLOR} Google Cloud / Firebase Billing Account ID cannot be empty."
        read -p "Billing Account ID: " user_billing_id
    done
    echo ""

    # Step 3: Cloudflare Domain & Zone Mappings
    echo -e "${BOLD}Step 3: Cloudflare Domains & Zone IDs${END_COLOR}"
    echo "Enter the domain mappings. You must add at least one domain."
    local cf_zones=()
    while true; do
        read -p "Domain name (e.g., danzaharia.com) [or press Enter to finish]: " cf_domain
        if [ -z "$cf_domain" ]; then
            if [ ${#cf_zones[@]} -eq 0 ]; then
                echo -e "${BOLD_RED}Required:${END_COLOR} You must configure at least one domain mapping."
                continue
            else
                break
            fi
        fi
        read -p "Cloudflare Zone ID for $cf_domain: " cf_zone_id
        while [ -z "$cf_zone_id" ]; do
            echo -e "${BOLD_RED}Required:${END_COLOR} Zone ID is required for $cf_domain."
            read -p "Cloudflare Zone ID: " cf_zone_id
        done
        cf_zones+=("$cf_domain:$cf_zone_id")
        echo -e "${BOLD_GREEN}Added:${END_COLOR} $cf_domain -> $cf_zone_id\n"
    done
    echo ""

    # Step 4: Cloudflare API Token
    echo -e "${BOLD}Step 4: Cloudflare API Token${END_COLOR}"
    echo "Enter your Cloudflare API Token (requires Zone.DNS Edit permissions)."
    read -p "Cloudflare API Token: " user_cf_token
    while [ -z "$user_cf_token" ]; do
        echo -e "${BOLD_RED}Required:${END_COLOR} Cloudflare API Token cannot be empty."
        read -p "Cloudflare API Token: " user_cf_token
    done
    echo ""

    # Generate .settings file
    cat <<EOF > "$SETTINGS_FILE"
# Global configuration and settings for setup scripts
# Auto-generated by host-manager.sh first-run setup

# Local directory where projects are scaffolded and stored
LOCAL_PROJECTS_DIR="$user_projects_dir"

# Google Cloud / Firebase Billing Account ID (used to link new projects to billing)
BILLING_ACCOUNT_ID="$user_billing_id"

# Cloudflare Zone mappings (format: "domain:zone_id")
CLOUDFLARE_ZONES=(
EOF
    for mapping in "${cf_zones[@]}"; do
        echo "  \"$mapping\"" >> "$SETTINGS_FILE"
    done
    cat <<EOF >> "$SETTINGS_FILE"
)

# Cloudflare API token with Edit DNS zone permissions
CLOUDFLARE_API_TOKEN="$user_cf_token"
EOF

    echo -e "${BOLD_GREEN}Configuration successfully written to $SETTINGS_FILE!${END_COLOR}"
    echo -e "Starting initialization...\n"
}

# Help handlers (fast exit, no dependencies needed)
show_general_help() {
    echo -e "${BOLD_CYAN}Host Manager CLI${END_COLOR} - Automated App Deployment & Maintenance"
    echo ""
    echo -e "${BOLD}Usage:${END_COLOR}"
    echo "  ./host-manager.sh [command] [options]"
    echo ""
    echo -e "${BOLD}Commands:${END_COLOR}"
    echo "  create-app   Scaffold and deploy a new Vite/React app with custom domains,"
    echo "               GitHub repo, and Firebase Hosting."
    echo "  remove-app   Decommission and remove an active app (local folder, Firebase"
    echo "               project, Cloudflare DNS, and update registry)."
    echo "  restore-app  Redeploy and restore an archived application from GitHub."
    echo "  list-apps    List all registered applications and their metadata."
    echo ""
    echo -e "${BOLD}Help on Commands:${END_COLOR}"
    echo "  ./host-manager.sh [command] --help     Show usage details for a specific command."
    echo ""
    echo -e "${BOLD}Global Options:${END_COLOR}"
    echo "  -h, --help   Show this general help message"
    echo ""
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_general_help
    exit 0
fi

if [ "$1" = "create-app" ] && { [ "$2" = "-h" ] || [ "$2" = "--help" ]; }; then
    echo -e "${BOLD}Usage:${END_COLOR}"
    echo "  ./host-manager.sh create-app [options]"
    echo ""
    echo -e "${BOLD}Options:${END_COLOR}"
    echo "  -n, --name NAME             App Name (Title Case) [Required]"
    echo "  -id, --id ID                App ID (lowercase-with-hyphens) [Optional, generated from name]"
    echo "  -urldomain, --domain DOM    Custom domain(s), comma-separated [Optional]"
    echo ""
    echo -e "${BOLD}Examples:${END_COLOR}"
    echo "  ./host-manager.sh create-app -n \"My Premium App\""
    echo "  ./host-manager.sh create-app -n \"Custom Domain App\" -id \"custom-app\" -urldomain \"custom-app.com\""
    exit 0
fi

if [ "$1" = "remove-app" ] && { [ "$2" = "-h" ] || [ "$2" = "--help" ]; }; then
    echo -e "${BOLD}Usage:${END_COLOR}"
    echo "  ./host-manager.sh remove-app [options]"
    echo ""
    echo -e "${BOLD}Options:${END_COLOR}"
    echo "  -id, --id ID                App ID of the application to remove [Required]"
    echo ""
    echo -e "${BOLD}Examples:${END_COLOR}"
    echo "  ./host-manager.sh remove-app -id \"my-app\""
    exit 0
fi

if [ "$1" = "restore-app" ] && { [ "$2" = "-h" ] || [ "$2" = "--help" ]; }; then
    echo -e "${BOLD}Usage:${END_COLOR}"
    echo "  ./host-manager.sh restore-app [options]"
    echo ""
    echo -e "${BOLD}Options:${END_COLOR}"
    echo "  -id, --id ID                App ID of the application to restore [Required]"
    echo ""
    echo -e "${BOLD}Examples:${END_COLOR}"
    echo "  ./host-manager.sh restore-app -id \"my-app\""
    exit 0
fi

if [ "$1" = "list-apps" ] && { [ "$2" = "-h" ] || [ "$2" = "--help" ]; }; then
    echo -e "${BOLD}Usage:${END_COLOR}"
    echo "  ./host-manager.sh list-apps [options]"
    echo ""
    echo -e "${BOLD}Options:${END_COLOR}"
    echo "  --status active|removed|all  Filter apps by status (default: active)"
    echo "  --json                       Output the list of apps in raw JSON format"
    echo ""
    echo -e "${BOLD}Examples:${END_COLOR}"
    echo "  ./host-manager.sh list-apps"
    echo "  ./host-manager.sh list-apps --status removed"
    echo "  ./host-manager.sh list-apps --json"
    exit 0
fi

# Source settings
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SETTINGS_FILE="$SCRIPT_DIR/.settings"
if [ ! -f "$SETTINGS_FILE" ]; then
    if [ "$INTERACTIVE" = true ]; then
        run_setup_stepper
    else
        echo "Cannot find settings at $SETTINGS_FILE. Please run host-manager.sh interactively first to complete setup."
        exit 1
    fi
fi

source "$SETTINGS_FILE"

if [ -z "$LOCAL_PROJECTS_DIR" ] || [ -z "$BILLING_ACCOUNT_ID" ] || [ ${#CLOUDFLARE_ZONES[@]} -eq 0 ]; then
    echo "LOCAL_PROJECTS_DIR, BILLING_ACCOUNT_ID, or CLOUDFLARE_ZONES not set properly in .settings"
    exit 1
fi

eval LOCAL_PROJECTS_DIR="$LOCAL_PROJECTS_DIR"
REGISTRY_DIR="$SCRIPT_DIR/apps-registry"
REGISTRY_FILE="$REGISTRY_DIR/apps-registry.json"

# Validate tools
for cmd in gh gcloud jq firebase; do
    if ! command -v $cmd &>/dev/null; then
        echo "$cmd CLI not found. Please install it."
        exit 1
    fi
done

# --- Startup Sync ---
GITHUB_USER=$(gh api user --jq .login 2>/dev/null)
if [ -z "$GITHUB_USER" ]; then
    echo "GitHub CLI (gh) is not authenticated. Run 'gh auth login' first."
    exit 1
fi

if [ ! -d "$REGISTRY_DIR" ]; then
    echo "Registry repository not found locally. Searching GitHub..."
    if ! gh repo view "$GITHUB_USER/apps-registry" &>/dev/null; then
        echo "Creating private GitHub repository: apps-registry..."
        mkdir -p "$REGISTRY_DIR"
        cd "$REGISTRY_DIR"
        git init
        git checkout -b main
        echo "[]" > apps-registry.json
        git add apps-registry.json
        git commit -m "Initialize registry"
        gh repo create "apps-registry" --private --source=. --remote=origin --push >/dev/null 2>&1
        cd "$SCRIPT_DIR"
    else
        echo "Cloning apps-registry from GitHub..."
        gh repo clone "$GITHUB_USER/apps-registry" "$REGISTRY_DIR" >/dev/null 2>&1
    fi
else
    echo "Syncing registry with GitHub..."
    cd "$REGISTRY_DIR"
    git pull >/dev/null 2>&1
    cd "$SCRIPT_DIR"
fi

# --- CLI Argument Handler ---
if [ "$#" -gt 0 ]; then
    INTERACTIVE=false
    CMD="$1"
    shift
    
    case "$CMD" in
        create-app)
            APP_NAME=""
            APP_ID=""
            URL_DOMAIN=""
            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    -n|--name) APP_NAME="$2"; shift ;;
                    -id|--id) APP_ID="$2"; shift ;;
                    -urldomain|--url-domain|--domain) URL_DOMAIN="$2"; shift ;;
                    *) echo "Unknown parameter passed to create-app: $1"; exit 1 ;;
                esac
                shift
            done
            
            if [ -z "$APP_NAME" ]; then
                echo -e "${BOLD_RED}ERROR:${END_COLOR} App Name is required. Use -n or --name."
                exit 1
            fi
            
            # Call setup-new-app.sh with arguments
            ARGS=("-n" "$APP_NAME")
            if [ -n "$APP_ID" ]; then
                ARGS+=("-id" "$APP_ID")
            fi
            if [ -n "$URL_DOMAIN" ]; then
                ARGS+=("-urldomain" "$URL_DOMAIN")
            fi
            
            ./setup-new-app.sh "${ARGS[@]}"
            exit $?
            ;;
            
        remove-app)
            APP_ID=""
            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    -id|--id) APP_ID="$2"; shift ;;
                    *) echo "Unknown parameter passed to remove-app: $1"; exit 1 ;;
                esac
                shift
            done
            
            if [ -z "$APP_ID" ]; then
                echo -e "${BOLD_RED}ERROR:${END_COLOR} App ID is required. Use -id or --id."
                exit 1
            fi
            
            # Check if app exists in registry first
            if [ -f "$REGISTRY_FILE" ]; then
                EXISTS=$(jq -r ".[] | select(.id == \"$APP_ID\" and .status == \"active\") | .id" "$REGISTRY_FILE")
                if [ -z "$EXISTS" ]; then
                    echo -e "${BOLD_RED}ERROR:${END_COLOR} Active app with ID '$APP_ID' not found in registry."
                    exit 1
                fi
            fi
            
            ./remove-app.sh --app-id "$APP_ID"
            exit $?
            ;;
            
        restore-app)
            APP_ID=""
            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    -id|--id) APP_ID="$2"; shift ;;
                    *) echo "Unknown parameter passed to restore-app: $1"; exit 1 ;;
                esac
                shift
            done
            
            if [ -z "$APP_ID" ]; then
                echo -e "${BOLD_RED}ERROR:${END_COLOR} App ID is required. Use -id or --id."
                exit 1
            fi
            
            # Find in registry
            if [ -f "$REGISTRY_FILE" ]; then
                name=$(jq -r ".[] | select(.id == \"$APP_ID\") | .name" "$REGISTRY_FILE")
                domain=$(jq -r ".[] | select(.id == \"$APP_ID\") | .domains | join(\", \")" "$REGISTRY_FILE")
                status=$(jq -r ".[] | select(.id == \"$APP_ID\") | .status" "$REGISTRY_FILE")
                
                if [ -z "$name" ] || [ "$name" = "null" ]; then
                    echo -e "${BOLD_RED}ERROR:${END_COLOR} App with ID '$APP_ID' not found in registry."
                    exit 1
                fi
                
                if [ "$status" = "active" ]; then
                    echo -e "${BOLD_RED}ERROR:${END_COLOR} App '$APP_ID' is already active."
                    exit 1
                fi
                
                restore_application "$APP_ID" "$name" "$domain"
                exit $?
            else
                echo -e "${BOLD_RED}ERROR:${END_COLOR} Registry file not found."
                exit 1
            fi
            ;;
            
        list-apps)
            STATUS_FILTER="active"
            OUTPUT_JSON=false
            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    --status) STATUS_FILTER="$2"; shift ;;
                    --json) OUTPUT_JSON=true ;;
                    *) echo "Unknown parameter passed to list-apps: $1"; exit 1 ;;
                esac
                shift
            done
            
            if [ ! -f "$REGISTRY_FILE" ] || [ ! -s "$REGISTRY_FILE" ]; then
                if [ "$OUTPUT_JSON" = true ]; then
                    echo "[]"
                else
                    echo "No applications recorded in registry."
                fi
                exit 0
            fi
            
            if [ "$OUTPUT_JSON" = true ]; then
                if [ "$STATUS_FILTER" = "all" ]; then
                    jq '.' "$REGISTRY_FILE"
                else
                    jq --arg filter "$STATUS_FILTER" '[.[] | select(.status == $filter)]' "$REGISTRY_FILE"
                fi
            else
                echo -e "${BOLD_CYAN}=== Registered Applications (Status: $STATUS_FILTER) ===${END_COLOR}"
                echo ""
                if [ "$STATUS_FILTER" = "all" ]; then
                    jq -r '.[] | "\(.id) [\(.status)]\n  Name:   \(.name)\n  Domain: https://\(.domains | join(", "))\n  Repo:   \(.github_repo | if type == "array" then map("https://" + .) | join(", ") else "https://" + . end)\n"' "$REGISTRY_FILE"
                else
                    jq -r --arg filter "$STATUS_FILTER" '.[] | select(.status == $filter) | "\(.id)\n  Name:   \(.name)\n  Domain: https://\(.domains | join(", "))\n  Repo:   \(.github_repo | if type == "array" then map("https://" + .) | join(", ") else "https://" + . end)\n"' "$REGISTRY_FILE"
                fi
            fi
            exit 0
            ;;
            
        *)
            echo -e "${BOLD_RED}ERROR:${END_COLOR} Unknown command '$CMD'."
            echo "Use -h or --help for usage details."
            exit 1
            ;;
    esac
fi

# Function to print the main menu
print_menu() {
    local header=$1
    local selected=$2
    shift 2
    local options=("$@")
    
    echo -e "\033[H\033[J" # Clear the screen
    echo -e "${BOLD_CYAN}  $header  ${END_COLOR}"
    echo " "
    
    for ((i = 0; i < ${#options[@]}; i++)); do
        if [ $i -eq $selected ]; then
            echo -e "  $(tput setaf 6)$(tput bold)→ ${options[i]}$(tput sgr0)"
        else
            echo -e "    ${options[i]}"
        fi
    done
    echo " "
}

# General TUI navigation
navigate_menu() {
    local header=$1
    shift 1
    local options=("$@")
    local selected=0

    while true; do
        print_menu "$header" $selected "${options[@]}"

        read -rsn1 input
        if [[ $input == $'\x1b' ]]; then
            read -rsn2 input # read arrow keys
            case $input in
                '[A') # Up arrow
                    ((selected--))
                    if [ $selected -lt 0 ]; then
                        selected=$(( ${#options[@]} - 1 ))
                    fi
                    ;;
                '[B') # Down arrow
                    ((selected++))
                    if [ $selected -ge ${#options[@]} ] ; then
                        selected=0
                    fi
                    ;;
            esac
        elif [[ $input == "" ]]; then # Enter key
            break
        fi
    done

    selected_option=$selected
}

# Interactive app viewing, deletion and redeployment (TUI with Ctrl+R detection)
view_apps_interactive() {
    local show_removed=false
    
    while true; do
        local filter="active"
        local header="Active Applications (Press Ctrl+R for Archives)"
        if [ "$show_removed" = true ]; then
            filter="removed"
            header="Archived Applications (Press Ctrl+R for Active)"
        fi
        
        # Load app names from registry
        if [ ! -f "$REGISTRY_FILE" ] || [ ! -s "$REGISTRY_FILE" ]; then
            echo "No applications recorded in registry."
            read -p "Press Enter to go back..."
            return
        fi
        
        local app_ids=()
        IFS=$'\n' read -rd '' -a app_ids <<<"$(jq -r ".[] | select(.status == \"$filter\") | .id" "$REGISTRY_FILE")"
        
        if [ ${#app_ids[@]} -eq 0 ] || [ "${app_ids[0]}" = "" ]; then
            app_ids=()
        fi
        
        # Draw TUI
        local selected=0
        while true; do
            echo -e "\033[H\033[J"
            echo -e "${BOLD_CYAN}  $header  ${END_COLOR}\n"
            
            if [ ${#app_ids[@]} -eq 0 ]; then
                echo "    (No applications found)"
            else
                for ((i=0; i<${#app_ids[@]}; i++)); do
                    if [ $i -eq $selected ]; then
                        echo -e "  $(tput setaf 6)$(tput bold)→ ${app_ids[i]}$(tput sgr0)"
                    else
                        echo -e "    ${app_ids[i]}"
                    fi
                done
            fi
            echo -e "\n  $(tput setaf 5)← Back$(tput sgr0)"
            
            # Read character (detecting Ctrl+R = \x12)
            read -rsn1 input
            if [[ "$input" == $'\x12' ]]; then
                # Toggle views
                if [ "$show_removed" = true ]; then
                    show_removed=false
                else
                    show_removed=true
                fi
                break # break inner loop to reload app ids
            elif [[ $input == $'\x1b' ]]; then
                read -rsn2 input
                case $input in
                    '[A')
                        ((selected--))
                        if [ $selected -lt 0 ]; then
                            selected=${#app_ids[@]}
                        fi
                        ;;
                    '[B')
                        ((selected++))
                        if [ $selected -gt ${#app_ids[@]} ]; then
                            selected=0
                        fi
                        ;;
                esac
            elif [[ $input == "" ]]; then
                # Enter selected option
                if [ $selected -eq ${#app_ids[@]} ]; then
                    return # Go Back
                fi
                
                local selected_id="${app_ids[$selected]}"
                show_details_and_actions "$selected_id" "$filter"
                break # Reload list after return from action
            fi
        done
    done
}

# Display details, delete or trigger restore
show_details_and_actions() {
    local app_id=$1
    local filter=$2
    
    while true; do
        local name=$(jq -r ".[] | select(.id == \"$app_id\") | .name" "$REGISTRY_FILE")
        local domain=$(jq -r ".[] | select(.id == \"$app_id\") | .domains | join(\", \")" "$REGISTRY_FILE")
        local firebase_project_id=$(jq -r ".[] | select(.id == \"$app_id\") | .firebase_project_id" "$REGISTRY_FILE")
        local gh_repo=$(jq -r ".[] | select(.id == \"$app_id\") | .github_repo | if type == \"array\" then map(\"https://\" + .) | join(\", \") else \"https://\" + . end" "$REGISTRY_FILE")
        local date=$(jq -r ".[] | select(.id == \"$app_id\") | .created_at" "$REGISTRY_FILE")
        
        echo -e "\033[H\033[J"
        echo -e "${BOLD_CYAN}=== Application Details ===${END_COLOR}\n"
        echo -e "Name:           ${BOLD}$name${END_COLOR}"
        echo -e "ID:             $app_id"
        if [ -n "$firebase_project_id" ] && [ "$firebase_project_id" != "null" ]; then
            echo -e "Firebase Proj:  $firebase_project_id"
        fi
        echo -e "Domain:         https://$domain"
        echo -e "GitHub Repo:    $gh_repo"
        echo -e "Created On:     $date"
        echo -e "Status:         $filter"
        echo " "
        
        if [ "$filter" = "removed" ]; then
            echo -e "  [R] Restore / Redeploy application"
            echo -e "  [Esc] Go back to list"
            echo " "
            
            read -rsn1 input
            if [[ "$input" == $'\x1b' ]] || [[ "$input" == "q" ]] || [[ "$input" == "Q" ]]; then
                return
            elif [[ "$input" == "r" ]] || [[ "$input" == "R" ]]; then
                echo " "
                read -p "Would you like to RESTORE/REDEPLOY this application? (y/N): " CONFIRM
                if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
                    restore_application "$app_id" "$name" "$domain"
                    return
                fi
            fi
        else
            echo -e "  [D] Delete / Remove application"
            echo -e "  [Esc] Go back to list"
            echo " "
            
            read -rsn1 input
            if [[ "$input" == $'\x1b' ]] || [[ "$input" == "q" ]] || [[ "$input" == "Q" ]]; then
                return
            elif [[ "$input" == "d" ]] || [[ "$input" == "D" ]]; then
                echo " "
                read -p "Would you like to DELETE/REMOVE this application? (y/N): " CONFIRM
                if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
                    ./remove-app.sh --app-id "$app_id"
                    # Refresh registry after removal
                    cd "$REGISTRY_DIR" && git pull >/dev/null 2>&1 && cd "$SCRIPT_DIR"
                    read -p "Press Enter to continue..."
                    return
                fi
            fi
        fi
    done
}

# Application restoration logic
restore_application() {
    local app_id=$1
    local app_name=$2
    local domain_name=$3
    
    echo -e "\nStarting restoration for $app_id..."
    
    # 1. Clone repository back
    local app_dir="$LOCAL_PROJECTS_DIR/$app_name"
    if [ -z "$app_name" ] || [ "$app_name" = "null" ]; then
        app_dir="$LOCAL_PROJECTS_DIR/$app_id"
    fi

    if [ -d "$app_dir" ]; then
        echo -e "${BOLD_RED}FAILED${END_COLOR} A folder already exists at $app_dir. Move or rename it first."
        press_enter_to_continue
        return 1
    fi
    
    echo "Cloning monorepo from GitHub..."
    if ! gh repo clone "$GITHUB_USER/$app_id" "$app_dir" >/dev/null 2>&1; then
        echo -e "${BOLD_RED}FAILED${END_COLOR} Cannot clone repository."
        press_enter_to_continue
        return 1
    fi
    
    # 2. Recreate Firebase Project
    local random_num=$(jot -r 1 10000 99999 2>/dev/null || shuf -i 10000-99999 -n 1 2>/dev/null || echo $((10000 + RANDOM % 90000)))
    local firebase_project_id="$app_id-$random_num"
    
    echo "Creating Firebase project $firebase_project_id..."
    if npx firebase-tools projects:create "$firebase_project_id" --display-name "$app_name"; then
        echo -e "${BOLD_GREEN}SUCCESS${END_COLOR} Created Firebase Project"
    else
        echo -e "${BOLD_RED}FAILED${END_COLOR} Cannot create Firebase project. It might already exist."
        rm -rf "$app_dir"
        press_enter_to_continue
        return 1
    fi
    
    echo "Linking Billing Account $BILLING_ACCOUNT_ID..."
    gcloud billing projects link "$firebase_project_id" --billing-account="$BILLING_ACCOUNT_ID" >/dev/null
    
    echo "Enabling required Google Cloud APIs (Firebase, Hosting, Cloud Functions, Cloud Run, Artifact Registry, Cloud Build, Billing Budgets)..."
    gcloud services enable \
        firebase.googleapis.com \
        firebasehosting.googleapis.com \
        cloudfunctions.googleapis.com \
        run.googleapis.com \
        artifactregistry.googleapis.com \
        cloudbuild.googleapis.com \
        cloudbilling.googleapis.com \
        billingbudgets.googleapis.com \
        eventarc.googleapis.com \
        --project="$firebase_project_id" >/dev/null 2>&1
    
    # Wait for API activation to propagate globally
    echo "Waiting for API propagation..."
    sleep 10
    
    echo "Creating Billing Budget of \$10..."
    if gcloud billing budgets create \
        --billing-account="$BILLING_ACCOUNT_ID" \
        --display-name="Budget for $firebase_project_id" \
        --budget-amount="10" \
        --filter-projects="projects/$firebase_project_id" \
        --threshold-rule=percent=0.5 \
        --threshold-rule=percent=0.9 \
        --threshold-rule=percent=1.0 \
        --project="$firebase_project_id" >/dev/null 2>&1; then
        echo -e "${BOLD_GREEN}SUCCESS${END_COLOR} Created Billing Budget"
    else
        echo -e "${BOLD_RED}WARNING:${END_COLOR} Failed to create Billing Budget"
    fi
    
    # Overwrite root configs for monorepo
    cat <<EOF > "$app_dir/.firebaserc"
{
  "projects": {
    "default": "$firebase_project_id"
  }
}
EOF
    mkdir -p "$app_dir/.github/workflows"
    cat <<EOF > "$app_dir/.github/workflows/deploy.yml"
name: Build and Deploy to Firebase

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/functions/package-lock.json

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Install Functions Dependencies
        run: npm ci
        working-directory: backend/functions

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: \${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --project $firebase_project_id --force
EOF
    
    # 3. Recreate Service Account Key
    echo "Configuring GCP service account and keys..."
    gcloud iam service-accounts create firebase-deployer \
        --description="Deployment Service Account" \
        --display-name="Firebase Deployer" \
        --project="$firebase_project_id" >/dev/null 2>&1
        
    echo "Configuring IAM policy bindings for Deployer Service Account..."
    for i in {1..5}; do
        if gcloud projects add-iam-policy-binding "$firebase_project_id" \
            --member="serviceAccount:firebase-deployer@$firebase_project_id.iam.gserviceaccount.com" \
            --role="roles/editor" >/dev/null 2>&1 && \
           gcloud projects add-iam-policy-binding "$firebase_project_id" \
            --member="serviceAccount:firebase-deployer@$firebase_project_id.iam.gserviceaccount.com" \
            --role="roles/iam.serviceAccountUser" >/dev/null 2>&1 && \
           gcloud projects add-iam-policy-binding "$firebase_project_id" \
            --member="serviceAccount:firebase-deployer@$firebase_project_id.iam.gserviceaccount.com" \
            --role="roles/cloudfunctions.admin" >/dev/null 2>&1 && \
           gcloud projects add-iam-policy-binding "$firebase_project_id" \
            --member="serviceAccount:firebase-deployer@$firebase_project_id.iam.gserviceaccount.com" \
            --role="roles/run.admin" >/dev/null 2>&1; then
            break
        fi
        sleep 2
    done
        
    echo "Generating service account keys..."
    for i in {1..5}; do
        if gcloud iam service-accounts keys create "$app_dir/firebase-key.json" \
            --iam-account="firebase-deployer@$firebase_project_id.iam.gserviceaccount.com" >/dev/null 2>&1; then
            break
        fi
        sleep 2
    done
    
    # 4. Upload keys back to GitHub Secrets
    echo "Updating secrets on GitHub repositories..."
    gh secret set FIREBASE_SERVICE_ACCOUNT_KEY --repo "$GITHUB_USER/$app_id" < "$app_dir/firebase-key.json" >/dev/null 2>&1
    rm -f "$app_dir/firebase-key.json"
    
    # 5. Connect domains on Firebase
    echo "Linking custom domains in Firebase Hosting..."
    ACCESS_TOKEN=$(gcloud auth print-access-token 2>/dev/null)
    if [ -n "$ACCESS_TOKEN" ]; then
        for mapping in "${CLOUDFLARE_ZONES[@]}"; do
            base_domain="${mapping%%:*}"
            target_domain="$app_id.$base_domain"
            echo "Registering $target_domain..."
            response=$(curl -s -w "\n%{http_code}" -X POST "https://firebasehosting.googleapis.com/v1beta1/projects/$firebase_project_id/sites/$firebase_project_id/customDomains?customDomainId=$target_domain" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -H "X-Goog-User-Project: $firebase_project_id" \
                -H "Content-Type: application/json" \
                -d "{}")
            code=$(echo "$response" | tail -n 1)
            body=$(echo "$response" | head -n -1)
            if [ "$code" -ne 200 ] && [ "$code" -ne 201 ]; then
                echo -e "${BOLD_RED}WARNING:${END_COLOR} Failed to register $target_domain (HTTP $code)"
                echo "Details: $body"
            else
                echo -e "${BOLD_GREEN}SUCCESS${END_COLOR} Registered $target_domain"
            fi
        done
    fi
    
    # 6. Re-configure Cloudflare records for domains
    if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
        for mapping in "${CLOUDFLARE_ZONES[@]}"; do
            base_domain="${mapping%%:*}"
            ZONE_ID="${mapping#*:}"
            
            if [ -n "$ZONE_ID" ]; then
                target_domain="$app_id.$base_domain"
                echo "Creating Cloudflare CNAME record for $target_domain..."
                response=$(curl -s -w "\n%{http_code}" -X POST "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records" \
                    -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
                    -H "Content-Type: application/json" \
                    --data "{\"type\":\"CNAME\",\"name\":\"$target_domain\",\"content\":\"$firebase_project_id.web.app\",\"ttl\":1,\"proxied\":false}")
                code=$(echo "$response" | tail -n 1)
                body=$(echo "$response" | head -n -1)
                if [ "$code" -ne 200 ] && [ "$code" -ne 201 ]; then
                    echo -e "${BOLD_RED}WARNING:${END_COLOR} Failed to create Cloudflare CNAME record for $target_domain (HTTP $code)"
                    echo "Details: $body"
                else
                    echo -e "${BOLD_GREEN}SUCCESS${END_COLOR} Created Cloudflare DNS record (DNS-only) for $target_domain"
                fi
            fi
        done
    fi
    
    # 7. Update status in registry
    echo "Updating status in synchronized registry..."
    cd "$REGISTRY_DIR"
    jq --arg f_pid "$firebase_project_id" --arg app_id "$app_id" 'map(if .id == $app_id and .status == "removed" then .status = "active" | .firebase_project_id = $f_pid else . end)' apps-registry.json > apps-registry.tmp.json && mv apps-registry.tmp.json apps-registry.json
    git add apps-registry.json
    git commit -m "Restore app: $app_id"
    git push >/dev/null 2>&1
    cd "$SCRIPT_DIR"
    
    # 8. Trigger deployment push
    echo "Triggering automated deployments on GitHub..."
    (cd "$app_dir" && git add .firebaserc .github/workflows/deploy.yml && git commit -m "Update Firebase project ID for restore" && git push origin main) >/dev/null 2>&1
    
    echo -e "${BOLD_GREEN}SUCCESS${END_COLOR} $app_id has been fully restored and is redeploying!"
    press_enter_to_continue
    return 0
}

# --- Main Program Loop ---
while true; do
    menu_options=("Create app" "View apps" "Exit")
    navigate_menu "Let Dan Code!" "${menu_options[@]}"
    selection=$selected_option

    case $selection in
        0)
            ./setup-new-app.sh
            # Pull latest registry updates after creation completes
            cd "$REGISTRY_DIR" && git pull >/dev/null 2>&1 && cd "$SCRIPT_DIR"
            read -p "Press Enter to return to menu..."
            ;;
        1)
            view_apps_interactive
            ;;
        2)
            echo "Exiting..."
            break
            ;;
    esac
done
